"""init tables

Revision ID: 19bcbc969eff
Revises: 
Create Date: 2026-09-05 17:00:48.463174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bcbc969eff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('degree', sa.String(length=20), nullable=True, comment='最高学历'),
    sa.Column('school', sa.String(length=100), nullable=True, comment='毕业院校'),
    sa.Column('major', sa.String(length=100), nullable=True, comment='专业'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='入学时间'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='毕业时间'),
    sa.Column('main_courses', sa.Text(), nullable=True, comment='主修核心课程'),
    sa.Column('honors', sa.Text(), nullable=True, comment='荣誉/奖学金'),
    sa.Column('gpa', sa.String(length=20), nullable=True, comment='学业成绩'),
    sa.Column('campus_projects', sa.Text(), nullable=True, comment='校园项目/竞赛/社团'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='教育经历表'
    )
    op.create_index(op.f('ix_educations_user_id'), 'educations', ['user_id'], unique=False)
    op.create_table('guidance_chats',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('chat_type', sa.String(length=20), nullable=False, comment='类型：companion / other'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：ongoing / finished'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='就业指导会话表'
    )
    op.create_index(op.f('ix_guidance_chats_user_id'), 'guidance_chats', ['user_id'], unique=False)
    op.create_table('guidance_contents',
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='类型：article / music / video'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='分类：psychology / positive / skill'),
    sa.Column('cover_url', sa.String(length=255), nullable=True, comment='封面图URL'),
    sa.Column('content_url', sa.String(length=255), nullable=True, comment='内容地址'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='上架状态：0下架 1上架'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='就业指导内容表'
    )
    op.create_table('guidance_messages',
    sa.Column('chat_id', sa.BigInteger(), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=10), nullable=False, comment='角色：ai / user'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='陪伴/指导消息表'
    )
    op.create_index(op.f('ix_guidance_messages_chat_id'), 'guidance_messages', ['chat_id'], unique=False)
    op.create_table('interview_feedbacks',
    sa.Column('interview_id', sa.BigInteger(), nullable=False, comment='面试ID'),
    sa.Column('question_index', sa.Integer(), nullable=False, comment='题号'),
    sa.Column('question_text', sa.Text(), nullable=True, comment='题目内容'),
    sa.Column('user_answer_summary', sa.Text(), nullable=True, comment='用户回答摘要'),
    sa.Column('total_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='本题总分'),
    sa.Column('content_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='内容质量分'),
    sa.Column('logic_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='逻辑结构分'),
    sa.Column('expression_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='表达沟通分'),
    sa.Column('professional_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='专业匹配分'),
    sa.Column('highlights', sa.Text(), nullable=True, comment='亮点'),
    sa.Column('issues', sa.Text(), nullable=True, comment='主要问题'),
    sa.Column('suggestions', sa.Text(), nullable=True, comment='改进建议'),
    sa.Column('sample_answer', sa.Text(), nullable=True, comment='示范回答'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='面试逐题点评表'
    )
    op.create_index(op.f('ix_interview_feedbacks_interview_id'), 'interview_feedbacks', ['interview_id'], unique=False)
    op.create_table('interview_messages',
    sa.Column('interview_id', sa.BigInteger(), nullable=False, comment='面试ID'),
    sa.Column('role', sa.String(length=10), nullable=False, comment='角色：ai / user'),
    sa.Column('interviewer_name', sa.String(length=50), nullable=True, comment='面试官标识（群面：A/B/C）'),
    sa.Column('question_index', sa.Integer(), nullable=True, comment='所属题号'),
    sa.Column('message_type', sa.String(length=20), nullable=True, comment='类型：question / answer / followup / score'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('asr_text', sa.Text(), nullable=True, comment='语音转文字原文'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='面试对话记录表'
    )
    op.create_index(op.f('ix_interview_messages_interview_id'), 'interview_messages', ['interview_id'], unique=False)
    op.create_table('interview_reports',
    sa.Column('interview_id', sa.BigInteger(), nullable=False, comment='面试ID'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='总分'),
    sa.Column('overall_comment', sa.Text(), nullable=True, comment='整体评价'),
    sa.Column('core_suggestions', sa.Text(), nullable=True, comment='3条核心改进建议'),
    sa.Column('next_practice_suggestions', sa.Text(), nullable=True, comment='下次练习建议'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id'),
    comment='面试报告表'
    )
    op.create_table('interviews',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('interview_mode', sa.String(length=20), nullable=False, comment='模式：one_to_one / group'),
    sa.Column('target_position', sa.String(length=100), nullable=True, comment='面试岗位'),
    sa.Column('interview_round', sa.String(length=20), nullable=True, comment='轮次：hr / tech / final'),
    sa.Column('interview_style', sa.String(length=20), nullable=True, comment='风格：formal / casual'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：ongoing / finished / cancelled'),
    sa.Column('total_questions', sa.Integer(), nullable=False, comment='题目总数'),
    sa.Column('current_question', sa.Integer(), nullable=False, comment='当前题号'),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='总分'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='面试会话表'
    )
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('job_preferences',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('target_industry', sa.String(length=100), nullable=True, comment='意向行业'),
    sa.Column('company_type', sa.String(length=50), nullable=True, comment='企业类型'),
    sa.Column('accept_overtime', sa.Boolean(), nullable=True, comment='是否接受加班'),
    sa.Column('accept_business_trip', sa.Boolean(), nullable=True, comment='是否接受出差'),
    sa.Column('accept_relocation', sa.Boolean(), nullable=True, comment='是否接受异地工作'),
    sa.Column('interview_round_pref', sa.String(length=50), nullable=True, comment='面试轮次偏好：hr / tech / final'),
    sa.Column('interview_style', sa.String(length=20), nullable=True, comment='面试风格：formal / casual'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='求职偏好表'
    )
    op.create_table('memberships',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('plan_type', sa.String(length=20), nullable=False, comment='套餐：free / vip'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='生效时间'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='到期时间'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：0失效 1生效'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='会员表'
    )
    op.create_table('orders',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('order_no', sa.String(length=64), nullable=False, comment='订单号'),
    sa.Column('plan_type', sa.String(length=20), nullable=False, comment='套餐类型'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='金额（元）'),
    sa.Column('pay_status', sa.SmallInteger(), nullable=False, comment='支付状态：0待支付 1已支付 2已取消'),
    sa.Column('pay_channel', sa.String(length=20), nullable=True, comment='支付渠道：wechat / alipay'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no'),
    comment='订单表'
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('profile_extras',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('self_assessment', sa.Text(), nullable=True, comment='个人优缺点自评'),
    sa.Column('career_plan', sa.Text(), nullable=True, comment='职业规划与发展方向'),
    sa.Column('hobbies', sa.Text(), nullable=True, comment='兴趣爱好'),
    sa.Column('specialties', sa.Text(), nullable=True, comment='个人特长'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='补充信息表'
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='姓名'),
    sa.Column('gender', sa.SmallInteger(), nullable=True, comment='性别：0未知 1男 2女'),
    sa.Column('age', sa.SmallInteger(), nullable=True, comment='年龄'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='常用邮箱'),
    sa.Column('target_position', sa.String(length=100), nullable=True, comment='意向岗位'),
    sa.Column('target_city', sa.String(length=50), nullable=True, comment='期望工作城市'),
    sa.Column('expected_salary_min', sa.Numeric(precision=10, scale=2), nullable=True, comment='期望薪资下限'),
    sa.Column('expected_salary_max', sa.Numeric(precision=10, scale=2), nullable=True, comment='期望薪资上限'),
    sa.Column('available_date', sa.String(length=50), nullable=True, comment='可到岗时间'),
    sa.Column('job_seeker_type', sa.String(length=20), nullable=True, comment='求职身份：fresh / graduate / career_change / employed'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='基础个人信息表'
    )
    op.create_table('real_interviews',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('interviewer_id', sa.BigInteger(), nullable=True, comment='真人面试官ID'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='预约时间'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending / confirmed / cancelled / finished'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='真人模拟面试预约表'
    )
    op.create_index(op.f('ix_real_interviews_user_id'), 'real_interviews', ['user_id'], unique=False)
    op.create_table('resume_analyses',
    sa.Column('resume_id', sa.BigInteger(), nullable=False, comment='简历ID'),
    sa.Column('total_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='综合评分'),
    sa.Column('layout_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='排版分'),
    sa.Column('expression_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='表达分'),
    sa.Column('highlight_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='亮点分'),
    sa.Column('match_score', sa.Numeric(precision=4, scale=1), nullable=True, comment='匹配度分'),
    sa.Column('optimized_content', sa.Text(), nullable=True, comment='优化版简历内容'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id'),
    comment='简历分析结果表'
    )
    op.create_table('resume_suggestions',
    sa.Column('analysis_id', sa.BigInteger(), nullable=False, comment='分析ID'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='分类：layout / expression / highlight / match'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='建议标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='建议内容'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='简历优化建议表'
    )
    op.create_index(op.f('ix_resume_suggestions_analysis_id'), 'resume_suggestions', ['analysis_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_url', sa.String(length=255), nullable=True, comment='对象存储URL'),
    sa.Column('file_type', sa.String(length=10), nullable=True, comment='类型：pdf / word'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小（字节）'),
    sa.Column('upload_status', sa.String(length=20), nullable=False, comment='上传状态：uploading / uploaded / failed'),
    sa.Column('parse_status', sa.String(length=20), nullable=False, comment='解析状态：pending / parsing / done / failed'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='简历表'
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('self_introductions',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('duration_type', sa.String(length=20), nullable=False, comment='时长：1min / 3min'),
    sa.Column('scenario', sa.String(length=20), nullable=False, comment='场景：campus / social / career_change / english'),
    sa.Column('content', sa.Text(), nullable=True, comment='自我介绍内容'),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False, comment='是否AI生成：0否 1是'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='智能自我介绍表'
    )
    op.create_index(op.f('ix_self_introductions_user_id'), 'self_introductions', ['user_id'], unique=False)
    op.create_table('third_party_accounts',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='平台：wechat / qq'),
    sa.Column('open_id', sa.String(length=128), nullable=False, comment='第三方OpenID'),
    sa.Column('union_id', sa.String(length=128), nullable=True, comment='微信UnionID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'open_id', name='uk_provider_open'),
    comment='第三方登录绑定表'
    )
    op.create_index(op.f('ix_third_party_accounts_user_id'), 'third_party_accounts', ['user_id'], unique=False)
    op.create_table('user_certificates',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('cert_name', sa.String(length=100), nullable=False, comment='证书名称'),
    sa.Column('cert_type', sa.String(length=20), nullable=True, comment='类型：vocational / english / computer'),
    sa.Column('issue_date', sa.Date(), nullable=True, comment='获取时间'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='证书表'
    )
    op.create_index(op.f('ix_user_certificates_user_id'), 'user_certificates', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('skill_name', sa.String(length=50), nullable=False, comment='技能名称'),
    sa.Column('skill_type', sa.String(length=20), nullable=False, comment='类型：professional / office / language'),
    sa.Column('level', sa.String(length=20), nullable=True, comment='熟练程度'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='技能表'
    )
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号（第三方登录可为空）'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希（第三方登录为空）'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='账号状态：0禁用 1正常'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    comment='用户账号表'
    )
    op.create_table('verification_codes',
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('code', sa.String(length=10), nullable=False, comment='验证码'),
    sa.Column('scene', sa.String(length=20), nullable=False, comment='场景：login / register / reset_password'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='是否已使用：0否 1是'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='短信验证码表'
    )
    op.create_index(op.f('ix_verification_codes_phone'), 'verification_codes', ['phone'], unique=False)
    op.create_table('wall_answers',
    sa.Column('question_id', sa.BigInteger(), nullable=False, comment='问题ID'),
    sa.Column('answerer_id', sa.BigInteger(), nullable=True, comment='回答者ID'),
    sa.Column('content', sa.Text(), nullable=True, comment='回答内容'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='真人问答墙回答表'
    )
    op.create_index(op.f('ix_wall_answers_question_id'), 'wall_answers', ['question_id'], unique=False)
    op.create_table('wall_questions',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='提问用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='问题标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='问题详情'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览数'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='真人问答墙问题表'
    )
    op.create_index(op.f('ix_wall_questions_user_id'), 'wall_questions', ['user_id'], unique=False)
    op.create_table('work_experiences',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('company_name', sa.String(length=100), nullable=True, comment='公司名称'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='岗位名称'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='入职时间'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='离职时间'),
    sa.Column('job_content', sa.Text(), nullable=True, comment='工作内容'),
    sa.Column('responsible_area', sa.Text(), nullable=True, comment='负责板块'),
    sa.Column('skills', sa.Text(), nullable=True, comment='实操技能'),
    sa.Column('tools', sa.Text(), nullable=True, comment='常用工具'),
    sa.Column('achievements', sa.Text(), nullable=True, comment='工作成果/业绩/项目案例'),
    sa.Column('leave_reason', sa.Text(), nullable=True, comment='离职原因（选填，供AI追问）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='实习/工作经历表'
    )
    op.create_index(op.f('ix_work_experiences_user_id'), 'work_experiences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_experiences_user_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_wall_questions_user_id'), table_name='wall_questions')
    op.drop_table('wall_questions')
    op.drop_index(op.f('ix_wall_answers_question_id'), table_name='wall_answers')
    op.drop_table('wall_answers')
    op.drop_index(op.f('ix_verification_codes_phone'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_user_certificates_user_id'), table_name='user_certificates')
    op.drop_table('user_certificates')
    op.drop_index(op.f('ix_third_party_accounts_user_id'), table_name='third_party_accounts')
    op.drop_table('third_party_accounts')
    op.drop_index(op.f('ix_self_introductions_user_id'), table_name='self_introductions')
    op.drop_table('self_introductions')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_resume_suggestions_analysis_id'), table_name='resume_suggestions')
    op.drop_table('resume_suggestions')
    op.drop_table('resume_analyses')
    op.drop_index(op.f('ix_real_interviews_user_id'), table_name='real_interviews')
    op.drop_table('real_interviews')
    op.drop_table('profiles')
    op.drop_table('profile_extras')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('memberships')
    op.drop_table('job_preferences')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('interview_reports')
    op.drop_index(op.f('ix_interview_messages_interview_id'), table_name='interview_messages')
    op.drop_table('interview_messages')
    op.drop_index(op.f('ix_interview_feedbacks_interview_id'), table_name='interview_feedbacks')
    op.drop_table('interview_feedbacks')
    op.drop_index(op.f('ix_guidance_messages_chat_id'), table_name='guidance_messages')
    op.drop_table('guidance_messages')
    op.drop_table('guidance_contents')
    op.drop_index(op.f('ix_guidance_chats_user_id'), table_name='guidance_chats')
    op.drop_table('guidance_chats')
    op.drop_index(op.f('ix_educations_user_id'), table_name='educations')
    op.drop_table('educations')
    # ### end Alembic commands ###
